### ISSUE TITLE
Ignoring Regions with {% # @prettify-ignore-start %} not working

### ISSUE THREAD

**Issue by MaxDesignFR** [panoply/esthetic#30]
In my testings `{% # @prettify-ignore-start %} / {% # @prettify-ignore-end %}` did not work, whereas `<!-- @prettify-ignore-start --> / <!-- @prettify-ignore-end -->` and other available methods seem to work properly.

That being said, I'm also not able to comment anything else on separate lines ; because snippets of code to exclude usually have somethings to be said about, or some kind of explanation about why it's excluded:
```
{% comment %} 
   @prettify-ignore-start
   Bla bla bla...
{% endcomment %}
```

**Comment by panoply** [comment]
Making some noise of this one @MaxDesignFR will you be available sometime soon? Need some help in test cases and the groundwork you've done so far has been a tremendous help. 

I will be patching this this evening and can shoot you over a build.

**Comment by panoply** [comment]
Fixed and support in Æsthetic to be available in the RC. 

### HTML Ignore Next

Ignore Next line using HTML comments: 

**Test Snapshots**: 
https://github.com/panoply/esthetic/blob/next/tests/cases/html/snapshots/ignore-next.test.mjs.md

```html
<!-- esthetic-ignore-next -->
```

### HTML Ignore Region

Ignore regions using HTML comments: 

**Test Snapshots**:
 https://github.com/panoply/esthetic/blob/next/tests/cases/html/snapshots/ignore-region.test.mjs.md

```html
<!-- esthetic-ignore-start -->

<!-- esthetic-ignore-end -->
```

### Liquid Ignore Next

Ignore next line using Liquid Line and Block Comments

**Test Snapshots**: 
https://github.com/panoply/esthetic/blob/next/tests/cases/liquid/snapshots/ignore-next.test.mjs.md

```liquid
{% comment %} esthetic-ignore-next {% endcomment %}
```

Also support Liquid Line comments

```liquid
{% # esthetic-ignore-next %}
```

### Liquid Ignore Region

Ignore regions, only support Liquid block comment for now. 

**Test Snapshots**: 
https://github.com/panoply/esthetic/blob/next/tests/cases/liquid/snapshots/ignore-region.test.mjs.md

```liquid
{% comment %} esthetic-ignore-start {% endcomment %}

{% comment %} esthetic-ignore-end {% endcomment %}
```

--- 

In addition rules are exposed for additional ignores:

```jsonc
{
  "liquid": {
    "ignoreTagList": [] // list of liquid tag names to ignore
  },
  "markup": {
     "ignoredCSS": false, // skip formatting of <style> code blocks
     "ignoredJS": false, // skip formatting of <script> code blocks
     "ignoredJSON": false // skip formatting of <script type="application/json"> identifiable code blocks
  }
}
```

More information to come in the official documentation:

https://æsthetic.dev
