### ISSUE TITLE
{% # @prettify-ignore %} adds a bracket or a new line at the end of file

### ISSUE THREAD

**Issue by MaxDesignFR** [panoply/esthetic#33]
On file save (settings to format on save), it seems `{% # @prettify-ignore %}` (placed first line of file) either adds a closing bracket or a new line at the end of the file:

![X6tSKY](https://user-images.githubusercontent.com/46461193/193045233-5b252bae-4c97-4b73-95e4-18db4dfc3e3b.gif)

**Comment by panoply** [comment]
This one was unrelated to the Prettify and introduced in vscode. This [commit](https://github.com/panoply/vscode-liquid/pull/110/commits/a8d72ac7f90dab5ff169edced121795f659f5cb8) fixes it.
