### ISSUE TITLE
JSON formatting issue

### ISSUE THREAD

**Issue by elliottmejia** [panoply/esthetic#36]
After hitting save, I'm seeing this: 
`
{
            "type": "image_picker",
            "id": "image-preview",
            "label": "Image preview"
          }, {
            "type": "text",
            "id": "block-title",
            "label": "Title"
          }, {
`
instead of this: 
`
{
            "type": "image_picker",
            "id": "image-preview",
            "label": "Image preview"
          },
          {
            "type": "text",
            "id": "block-title",
            "label": "Title"
          },
`

**Comment by panoply** [comment]
Hey @Elliottmeija did you figure out the issue here?

**Comment by elliottmejia** [comment]
I closed the issue because unfortunately Github reformatted the JSON, which
is hilarious, but no.

Shopify, specifically, doesn’t like json out of this format:

},
{

However, prettify defaults to this format:

},{

**Comment by panoply** [comment]
You need to adjust the beautification rules, specifically by setting `json.braceAllman` to `true`.  Shopify JSON structures don't necessarily require a specific format, any valid JSON will do. If Shopify recommends expanded structures, then it is only a recommendation, grain of salt it..

**Comment by elliottmejia** [comment]
Yeah, totally understand it’s just a warning, but it’s something I like
clearing and I personally prefer multi-line format.

Thank you for the tip!
