### ISSUE TITLE
Support Liquid Line Comment Ignores

### ISSUE THREAD

**Issue by panoply** [panoply/esthetic#59]
### Description

It seems that this is not currently supported in local versions. The current supported inline comment lists are as follows:

```
{% # esthetic-ignore %}

{% comment %} esthetic-ignore {% endcomment %}
{% comment %} esthetic-ignore-start {% endcomment %}
{% comment %} esthetic-ignore-end {% endcomment %}
{% comment %} esthetic-ignore-next {% endcomment %}

<!-- esthetic-ignore -->
<!-- esthetic-ignore-start -->
<!-- esthetic-ignore-end -->
<!-- esthetic-ignore-next -->

/* esthetic-ignore */
/* esthetic-ignore-start  */
/* esthetic-ignore-end  */
/* esthetic-ignore-next  */

// esthetic-ignore 
// esthetic-ignore-start 
// esthetic-ignore-end 
// esthetic-ignore-next 

```

### Required 

Additional test cases need to be generated to ensure all comment ignores are behaving correctly, but most pressing here given use within vscode-liquid is liquid line comments. As per the above list, Liquid inline comments need support for:

```
{% # esthetic-ignore-start  %}    
{% # esthetic-ignore-end  %}
{% # esthetic-ignore-next  %}
```

**Comment by MOHAMMADALDREAI** [comment]
{% # esthetic-ignore %}

{% comment %} esthetic-ignore {% endcomment %}
{% comment %} esthetic-ignore-start {% endcomment %}
{% comment %} esthetic-ignore-end {% endcomment %}
{% comment %} esthetic-ignore-next {% endcomment %}






/* esthetic-ignore */
/* esthetic-ignore-start  */
/* esthetic-ignore-end  */
/* esthetic-ignore-next  */

// esthetic-ignore 
// esthetic-ignore-start 
// esthetic-ignore-end 
// esthetic-ignore-next
