### ISSUE TITLE
spam account

### ISSUE THREAD

**Issue by MOHAMMADALDREAI** [panoply/esthetic#63]

**Comment by MOHAMMADALDREAI** [comment]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Checklist** 
- [x] I have checked and made sure that the proposal adheres to this plugin's [principles](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/principles/index.md)

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by MOHAMMADALDREAI** [comment]
H

**Comment by panoply** [comment]
Unsure why you keep submitting issues to this repository. Nothing you've posted makes any sense. I'll need to restrict you from creating noise if it continues.
